/* Simple +/-/* expression language; parser evaluates constant expressions on the fly*/
/**
 *  Package and Import Specifications
 */
import java_cup.runtime.*;

/**
 *  Usercode Components
 */
parser code {:
    // Connect this parser to a scanner!
    Scanner s;
    Parser(Scanner s){ this.s=s; }
:}

/* define how to connect to the scanner! */
scan with {: return s.next_token(); :};

action code {:


        class Functions{
            int num=0;

            public String SetStringInParameters(String str)
            {
                String out,tmp;

                str=str.substring(0, str.lastIndexOf(")"));

                if(str == null || str.isEmpty()){return "";}


                out="String "+str;
                int index = out.indexOf(",");

                while (index >= 0) {

                    out=out.substring(0,index)+",String "+out.substring(index+1,out.length());
                    index = out.indexOf(",", index + 1);

                }
                return out;
            }
        }

        Functions fun=new Functions();




:}


/**
 *  Symbol Lists
 */

/* Terminals (tokens returned by the scanner). */
terminal            PLUS,LPAREN, RPAREN,STRING,RBRACKET,COMMA,IF,ELSE,PREFIX,SUFFIX,PARAMETERS_DECL;
terminal            IDENTIFIER;        // our scanner provides numbers as integers

/*  Non terminals */
non terminal            expr;
non terminal            function_decl;
non terminal            function_decls;
non terminal            function_call;
non terminal            parameters;
non terminal            parameters_decl;
non terminal            statement;
non terminal            programme;
non terminal             function_calls;
non terminal            main_body;
non terminal            parameters_call;
non terminal            object;
non terminal            if_statement;
non terminal            conditional_statement;

/**
 *  The Grammar Rules
 */


programme ::=main_body:mb {:System.out.println("public class Out {\t\n"+mb+"\n"+"}");:};

main_body   ::= function_decls:fd function_calls:fcs   {:RESULT="\tpublic static void main(String[] args) {\n"+fcs+"\n"+"\t}\n"+fd;:};

function_calls ::= function_call:fc function_calls:fcs {:RESULT="\t\tSystem.out.println("+fc+");\n"+fcs;:}
                   |function_call:fc                  {:RESULT="\t\tSystem.out.println("+fc+");\n";:}
                   ;



function_decls ::= function_decls:fds function_decl:fd                                                               {:RESULT=(String)fd+(String)fds;:}
                   |function_decl:fd                                                                               {:RESULT=(String)fd;:}
                   ;


function_decl ::=  IDENTIFIER:id LPAREN  PARAMETERS_DECL:pd  expr:in  RBRACKET                      {:RESULT="\tpublic static String "+id+"("+fun.SetStringInParameters((String)pd)+")"+
                                                                                                                                            "{\n"+"\t\t"+"return "+in+";"+"\n"+"\t}\n";:}
                   |IDENTIFIER:id LPAREN  RPAREN RBRACKET expr:in  RBRACKET                                        {:RESULT="\tpublic static String "+id+"("+")"+"{\n"+"\t\t"+"return "+in+";"+"\n"+"\t}\n";:}
                   ;



function_call ::=IDENTIFIER:id LPAREN parameters_call:p RPAREN  {:RESULT=id+"("+p+")";:}
                 |IDENTIFIER:id LPAREN  RPAREN                  {:RESULT=id+"("+")";:}
                 ;




parameters_call  ::= parameters_call:pc COMMA  statement:e   {:RESULT=pc+","+e;:}
                    |statement:e                              {:RESULT=e;:}
                    ;



if_statement ::=IF conditional_statement:cs RPAREN expr:e1 ELSE expr:e2  {:RESULT="("+"("+cs+")"+"?"+"("+e1+")"+":"+"("+e2+")"+")";:};


conditional_statement ::= statement:s1 PREFIX statement:s2 {:RESULT="("+s1+")"+".startsWith("+s2+")";:}
                        |statement:s1 SUFFIX statement:s2 {:RESULT="("+s1+")"+".endsWith("+s2+")";:}
                        ;





expr ::= statement:st                          {:RESULT=st;:}
       | if_statement:is                       {:RESULT=is;:}
       ;


statement    ::=statement:s PLUS object:o           {:RESULT=s+"+"+o;:}
            |object:o                               {:RESULT=o;:}
            |LPAREN statement:e RPAREN              {:RESULT="("+e+")";:}
            ;

object ::=   IDENTIFIER:id                          {:RESULT=id;:}
             |STRING:str                            {:RESULT=str;:}
             |function_call:fc                      {:RESULT=fc;:}
             ;


