
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int PAR_RBRACKET = 9;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int STRING = 5;
  public static final int RBRACKET = 6;
  public static final int COMMA = 8;
  public static final int error = 1;
  public static final int RPAREN = 4;
  public static final int IDENTIFIER = 10;
  public static final int LBRACKET = 7;
  public static final int LPAREN = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "LPAREN",
  "RPAREN",
  "STRING",
  "RBRACKET",
  "LBRACKET",
  "COMMA",
  "PAR_RBRACKET",
  "IDENTIFIER"
  };
}

