
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  int PAR_RBRACKET = 9;
  int PREFIX = 12;
  int EOF = 0;
  int PLUS = 2;
  int STRING = 5;
  int IF = 10;
  int RBRACKET = 6;
  int ELSE = 11;
  int COMMA = 8;
  int error = 1;
  int RPAREN = 4;
  int IDENTIFIER = 14;
  int SUFFIX = 13;
  int LBRACKET = 7;
  int LPAREN = 3;
  String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "LPAREN",
  "RPAREN",
  "STRING",
  "RBRACKET",
  "LBRACKET",
  "COMMA",
  "PAR_RBRACKET",
  "IF",
  "ELSE",
  "PREFIX",
  "SUFFIX",
  "IDENTIFIER"
  };
}

